name: 'Last successful commit'
description: 'Get the commit hash of the last successful workflow run on a given branch'
inputs:
  branch:  # branch to analyze
    description: 'Branch to get last successful commit from'
    required: false
    default: 'main'
  github_token:  # github token to use
    description: 'Your GitHub access token'
    required: true
  workflow_id:  # ID or filename of the workflow
    description: 'ID or filename of the workflow'
    required: true
  tag_pattern:
    description: 'Tag pattern to filter on'
    required: false
  current_tag:
    description: 'The current tag associated with the commit if it exists'
    required: false
outputs:
  commit_hash: # hash of the last successful workflow run
    description: 'Last successful commit'
runs:
  using: 'node20'
  main: 'dist/index.js'
